#!/bin/bash

#Find the location of CGL
LOCATION=$(cd ${0%/*} && echo $PWD/${0##*/})
DIR=`dirname "$LOCATION"`

#And the location of the binary we want to run
LOCATION=$(cd ${1%/*} && echo $PWD/${1##*/})
RUNTIME_DIR=`dirname "$LOCATION"`

if [ \! $CGL_CONFIG_FILE ]; then 
export CGL_CONFIG_FILE="$DIR/cgl.conf"
fi

cd $RUNTIME_DIR && LD_PRELOAD=$DIR/libcgl-capture.so ./`basename $@`
#cd $RUNTIME_DIR && LD_PRELOAD=$DIR/libcgl-capture.so gdb -ex run -quiet --args ./`basename $@`
