#!/bin/bash

SCRIPTNAME=rungl

DIR=$(dirname $0)
if [ ! -x ${DIR}/${SCRIPTNAME} ]; then
	DIR=$(dirname $(which symphony.sh))
fi

if [ ! -x ${DIR}/${SCRIPTNAME} ]; then
	echo Cant locate \"${DIR}/${SCRIPTNAME}\", giving up >&2
	exit 1
fi

echo Using clusterGL from ${DIR}...
for i in `seq 1 5`; do
	ssh dn$i "cd ${DIR} && DISPLAY=:0 ./GL $i > /dev/null" &
done
sleep 2
DISPLAY=:0 LD_PRELOAD="${DIR}/libGL.so.1" $@

for i in `seq 1 5`; do
	ssh dn$i "killall -9 GL"
done
